deploy:
  admin_prefix: "/admin"
  listen:
    host: "0.0.0.0"
    port: 9000
mysql:
  host: ""
  port: 0
  username: ""
  password: ""
  database: ""
redis:
  host: "127.0.0.1"
  port: 6379
  username: ""
  password: ""
  db: 0
jwt:
  secret: "DefaultJwtToken"
