package sys_config

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/Gary-Yez/go-admin/internal/bizconfig"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"reflect"
	"regexp"
	"strconv"
	"strings"
)

const generatedHeader = "// Code generated by go-admin configuration tools. DO NOT EDIT."

var fieldPattern = regexp.MustCompile("^[A-Z][A-Za-z0-9]*$")

var keyPattern = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9]*([._-][A-Za-z0-9]+)*$`)

// 新字段从 Key 生成 Go 名称，已有字段保留名称，避免影响业务调用。
func prepareFields(fields, existing []Field) error {
	byKey, byName := make(map[string]Field, len(existing)), make(map[string]Field, len(existing))
	for _, field := range existing {
		byKey[field.Key], byName[field.Name] = field, field
	}
	for i := range fields {
		field := &fields[i]
		field.Key = strings.TrimSpace(field.Key)
		field.Group = strings.TrimSpace(field.Group)
		field.Label = strings.TrimSpace(field.Label)
		field.Name = ""
		if previous, exists := byKey[field.Key]; exists {
			field.Name = previous.Name
			if field.Type != previous.Type {
				return errors.New("已有配置不允许直接修改类型，请新建配置并迁移调用")
			}
		}
		if field.Name == "" {
			if !keyPattern.MatchString(field.Key) {
				return errors.New("Key 须以英文字母开头，可使用字母、数字及点、下划线、短横线分隔")
			}
			for _, part := range strings.FieldsFunc(field.Key, func(r rune) bool { return r == '.' || r == '_' || r == '-' }) {
				field.Name += strings.ToUpper(part[:1]) + part[1:]
			}
		}
		if previous, exists := byName[field.Name]; exists && previous.Key != field.Key {
			return errors.New("已有字段不允许直接修改配置标识，请新增字段迁移")
		}
	}
	return nil
}

func render(fields []Field, typeName string) ([]byte, error) {
	var body, handles strings.Builder
	handles.WriteString("BaseConfig = &current.BaseConfig\n")
	names, keys := map[string]bool{"BaseConfig": true, "Init": true}, map[string]bool{}
	if baseConfigSchema == nil {
		return nil, errors.New("系统配置尚未初始化")
	}
	base := baseConfigSchema
	for _, field := range base.Fields {
		name := base.Type.FieldByIndex(field.Index).Name
		names[name] = true
		keys[field.Key] = true
	}
	for _, field := range fields {
		if len([]rune(field.Group)) > 100 {
			return nil, errors.New("分组不能超过 100 个字符")
		}
		if !fieldPattern.MatchString(field.Name) || names[field.Name] {
			return nil, errors.New("字段名称无效、重复或与内置字段冲突")
		}
		if strings.TrimSpace(field.Key) == "" || len(field.Key) > 191 || keys[field.Key] {
			return nil, errors.New("配置标识不能为空、重复或与内置配置冲突")
		}
		if strings.TrimSpace(field.Label) == "" {
			return nil, errors.New("配置名称不能为空")
		}
		if err := bizconfig.ValidateDefinition(field.Definition); err != nil {
			return nil, err
		}
		names[field.Name], keys[field.Key] = true, true
		value := string(field.Default)
		if field.Type == "string" {
			if err := json.Unmarshal(field.Default, &value); err != nil {
				return nil, err
			}
		}
		tag := fmt.Sprintf("config:%q label:%q default:%q description:%q", field.Key, field.Label, value, field.Description)
		if field.Group != "" {
			tag += fmt.Sprintf(" group:%q", field.Group)
		}
		if field.Control != "" {
			tag += fmt.Sprintf(" control:%q", field.Control)
			if len(field.Options) != 0 {
				options, err := json.Marshal(field.Options)
				if err != nil {
					return nil, err
				}
				tag += fmt.Sprintf(" options:%q", options)
			}
		}
		if field.Rows != 0 {
			tag += fmt.Sprintf(" rows:%q", strconv.Itoa(field.Rows))
		}
		tagLiteral := strconv.Quote(tag)
		if !strings.ContainsRune(tag, 96) {
			tagLiteral = string(rune(96)) + tag + string(rune(96))
		}
		fmt.Fprintf(&body, "%s admin.ConfigItem[%s] %s\n", field.Name, field.Type, tagLiteral)
		fmt.Fprintf(&handles, "%s = &current.%s\n", field.Name, field.Name)
	}
	source := fmt.Sprintf("%s\n\npackage settings\n\nimport admin %q\n\ntype %s struct {\nadmin.BaseConfig\n%s}\n\nvar current %s\n\nvar (\n%s)\n\nfunc init() {\nif err := admin.RegisterConfig(&current); err != nil {\npanic(err)\n}\n}\n", generatedHeader, "github.com/Gary-Yez/go-admin", typeName, body.String(), typeName, handles.String())
	return format.Source([]byte(source))
}

func parse(content []byte) ([]Field, string, error) {
	fields := []Field{}
	if len(content) == 0 {
		return fields, "config", nil
	}
	invalid := errors.New("config.go 不是受支持的配置结构文件，或包含额外代码")
	if !bytes.HasPrefix(content, []byte(generatedHeader)) {
		return nil, "", invalid
	}
	file, err := parser.ParseFile(token.NewFileSet(), "config.go", content, 0)
	if err != nil {
		return nil, "", err
	}
	typeName := ""
	for _, decl := range file.Decls {
		general, ok := decl.(*ast.GenDecl)
		if !ok || general.Tok != token.TYPE {
			continue
		}
		for _, spec := range general.Specs {
			named := spec.(*ast.TypeSpec)
			structure, ok := named.Type.(*ast.StructType)
			if !ok || named.Assign.IsValid() || named.Name.Name != "config" || typeName != "" {
				return nil, "", errors.New("config.go 应只定义一个私有 config 结构体")
			}
			typeName = named.Name.Name
			for _, field := range structure.Fields.List {
				if len(field.Names) == 0 {
					continue
				}
				if len(field.Names) != 1 || field.Tag == nil {
					return nil, "", invalid
				}
				tagText, err := strconv.Unquote(field.Tag.Value)
				if err != nil {
					return nil, "", err
				}
				tag := reflect.StructTag(tagText)
				item, ok := field.Type.(*ast.IndexExpr)
				if !ok {
					return nil, "", invalid
				}
				selector, ok := item.X.(*ast.SelectorExpr)
				if !ok || selector.Sel.Name != "ConfigItem" {
					return nil, "", invalid
				}
				pkg, ok := selector.X.(*ast.Ident)
				if !ok || pkg.Name != "admin" {
					return nil, "", invalid
				}
				var kind bytes.Buffer
				if err := format.Node(&kind, token.NewFileSet(), item.Index); err != nil {
					return nil, "", err
				}
				value := json.RawMessage(tag.Get("default"))
				if kind.String() == "string" {
					value, _ = json.Marshal(tag.Get("default"))
				}
				options := []bizconfig.Option{}
				if text := tag.Get("options"); text != "" {
					if err := json.Unmarshal([]byte(text), &options); err != nil {
						return nil, "", err
					}
				}
				rows := 0
				if text := tag.Get("rows"); text != "" {
					rows, err = strconv.Atoi(text)
					if err != nil {
						return nil, "", err
					}
				}
				fields = append(fields, Field{Name: field.Names[0].Name, Definition: bizconfig.Definition{Key: tag.Get("config"), Group: tag.Get("group"), Label: tag.Get("label"), Description: tag.Get("description"), Type: kind.String(), Control: tag.Get("control"), Rows: rows, Options: options, Default: value}})
			}
		}
	}
	if typeName == "" {
		return nil, "", errors.New("config.go 中未找到配置结构体")
	}
	canonical, err := render(fields, typeName)
	if err != nil {
		return nil, "", err
	}
	formatted, err := format.Source(content)
	if err != nil || !bytes.Equal(canonical, formatted) {
		return nil, "", invalid
	}
	return fields, typeName, nil
}
